//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingKernel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingKernel.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کالای {0} حساب تفصیلی تعیین نشده است..
        /// </summary>
        internal static string ex_commodity_no_accountingtafsillevelsdetails {
            get {
                return ResourceManager.GetString("ex_commodity_no_accountingtafsillevelsdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای شرکت {0} حساب تفصیلی تعیین نشده است..
        /// </summary>
        internal static string ex_company_no_accountingtafsillevelsdetails {
            get {
                return ResourceManager.GetString("ex_company_no_accountingtafsillevelsdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبدیل واحد شمارش پیدا نشد..
        /// </summary>
        internal static string ex_converting_unit_not_found {
            get {
                return ResourceManager.GetString("ex_converting_unit_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان تکراری است..
        /// </summary>
        internal static string ex_dupliatedname {
            get {
                return ResourceManager.GetString("ex_dupliatedname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت تکراری است..
        /// </summary>
        internal static string ex_dupliatedpriority {
            get {
                return ResourceManager.GetString("ex_dupliatedpriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر کد برای داده انتخابی وجود ندارد..
        /// </summary>
        internal static string ex_invalid_code_changing {
            get {
                return ResourceManager.GetString("ex_invalid_code_changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبدیل واحد شمارش نادرست است..
        /// </summary>
        internal static string ex_invalid_converting_unit {
            get {
                return ResourceManager.GetString("ex_invalid_converting_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف رکورد مورد نظر وجود ندارد..
        /// </summary>
        internal static string ex_invalid_delete_operation {
            get {
                return ResourceManager.GetString("ex_invalid_delete_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی ارسال نشده است..
        /// </summary>
        internal static string ex_no_record {
            get {
                return ResourceManager.GetString("ex_no_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از رکورد ارسالی در بخش های دیگر استفاده شده است..
        /// </summary>
        internal static string ex_record_already_used {
            get {
                return ResourceManager.GetString("ex_record_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری است..
        /// </summary>
        internal static string ex_replicate_code {
            get {
                return ResourceManager.GetString("ex_replicate_code", resourceCulture);
            }
        }
    }
}
