//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingKernel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingKernel.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال استقرار.
        /// </summary>
        internal static string AssetEstablishment {
            get {
                return ResourceManager.GetString("AssetEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای اموال.
        /// </summary>
        internal static string AssetGood {
            get {
                return ResourceManager.GetString("AssetGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه های کالای اموال.
        /// </summary>
        internal static string AssetGoodGroup {
            get {
                return ResourceManager.GetString("AssetGoodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت فایییییییید.
        /// </summary>
        internal static string btn_manageBank_11111 {
            get {
                return ResourceManager.GetString("btn_manageBank_11111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Cheque_Fund_Seperator {
            get {
                return ResourceManager.GetString("Cheque_Fund_Seperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف حساب.
        /// </summary>
        internal static string CompanyManagement {
            get {
                return ResourceManager.GetString("CompanyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد.
        /// </summary>
        internal static string DeleteRecordCaption {
            get {
                return ResourceManager.GetString("DeleteRecordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به حذف رکورد میباشید?.
        /// </summary>
        internal static string DeleteRecordMessage {
            get {
                return ResourceManager.GetString("DeleteRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم اسناد.
        /// </summary>
        internal static string DocumentForm {
            get {
                return ResourceManager.GetString("DocumentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        internal static string DocumentManagement {
            get {
                return ResourceManager.GetString("DocumentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کل تکراری است.
        /// </summary>
        internal static string DoubleCode {
            get {
                return ResourceManager.GetString("DoubleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        internal static string DoubleMaskType {
            get {
                return ResourceManager.GetString("DoubleMaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی مقادیر الزامی میباشد.
        /// </summary>
        internal static string ex_all_item_mandatory {
            get {
                return ResourceManager.GetString("ex_all_item_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش استهلاک تعیین نشده است..
        /// </summary>
        internal static string ex_amortizationmethod_not_selected {
            get {
                return ResourceManager.GetString("ex_amortizationmethod_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای اموال پیدا نشد..
        /// </summary>
        internal static string ex_assetgood_not_found {
            get {
                return ResourceManager.GetString("ex_assetgood_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش محاسبه انتخاب نشده است..
        /// </summary>
        internal static string ex_calculationtype_not_seletced {
            get {
                return ResourceManager.GetString("ex_calculationtype_not_seletced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر سفارش اجباری است..
        /// </summary>
        internal static string ex_cinventorymax_is_mandatory {
            get {
                return ResourceManager.GetString("ex_cinventorymax_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا پیدا نشد..
        /// </summary>
        internal static string ex_commodity_not_found {
            get {
                return ResourceManager.GetString("ex_commodity_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کالا را مشخص نمایید..
        /// </summary>
        internal static string ex_commodity_type_is_mandatory {
            get {
                return ResourceManager.GetString("ex_commodity_type_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده پیدا نشد..
        /// </summary>
        internal static string ex_company_not_found {
            get {
                return ResourceManager.GetString("ex_company_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف فروش اجباری است..
        /// </summary>
        internal static string ex_cordermax_is_mandatory {
            get {
                return ResourceManager.GetString("ex_cordermax_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل سفارش اجباری است..
        /// </summary>
        internal static string ex_cordermin_is_mandatory {
            get {
                return ResourceManager.GetString("ex_cordermin_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه سفارش اجباری است..
        /// </summary>
        internal static string ex_corderpoint_is_mandatory {
            get {
                return ResourceManager.GetString("ex_corderpoint_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نادرست است..
        /// </summary>
        internal static string ex_count_is_not_valid {
            get {
                return ResourceManager.GetString("ex_count_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه بحرانی وارد نشده است..
        /// </summary>
        internal static string ex_cpointcritical_is_mandatory {
            get {
                return ResourceManager.GetString("ex_cpointcritical_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه بحرانی باید از نقطه سفارش کم تر باشد..
        /// </summary>
        internal static string ex_critical_greater_than_order_point {
            get {
                return ResourceManager.GetString("ex_critical_greater_than_order_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حساب مورد نظر چکی با سریال وارد شده وجود دارد..
        /// </summary>
        internal static string ex_dupliacted_serial {
            get {
                return ResourceManager.GetString("ex_dupliacted_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال قبلا برای این گروه ثبت شده میباشد.
        /// </summary>
        internal static string ex_dupliacted_year {
            get {
                return ResourceManager.GetString("ex_dupliacted_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان تکراری است..
        /// </summary>
        internal static string ex_dupliatedname {
            get {
                return ResourceManager.GetString("ex_dupliatedname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری است..
        /// </summary>
        internal static string ex_duplicate_code {
            get {
                return ResourceManager.GetString("ex_duplicate_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام وارد شده تکراری است..
        /// </summary>
        internal static string ex_duplicate_name {
            get {
                return ResourceManager.GetString("ex_duplicate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری است..
        /// </summary>
        internal static string ex_duplicated_code {
            get {
                return ResourceManager.GetString("ex_duplicated_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه اصلی تکراری است..
        /// </summary>
        internal static string ex_duplicated_main_group_name {
            get {
                return ResourceManager.GetString("ex_duplicated_main_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری است..
        /// </summary>
        internal static string ex_duplicated_subsidiary_group_code {
            get {
                return ResourceManager.GetString("ex_duplicated_subsidiary_group_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه فرعی تکراری است..
        /// </summary>
        internal static string ex_duplicated_subsidiary_group_name {
            get {
                return ResourceManager.GetString("ex_duplicated_subsidiary_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استهلاک انباشته تعیین نشده است..
        /// </summary>
        internal static string ex_empty_accumulative_amortization {
            get {
                return ResourceManager.GetString("ex_empty_accumulative_amortization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ استهلاک تعیین نشده است..
        /// </summary>
        internal static string ex_empty_amortizationrate {
            get {
                return ResourceManager.GetString("ex_empty_amortizationrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دارایی تعیین نشده است..
        /// </summary>
        internal static string ex_empty_assetno {
            get {
                return ResourceManager.GetString("ex_empty_assetno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اموال تعیین نشده است..
        /// </summary>
        internal static string ex_empty_assetnumber {
            get {
                return ResourceManager.GetString("ex_empty_assetnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش اسقاط تعیین نشده است..
        /// </summary>
        internal static string ex_empty_decay {
            get {
                return ResourceManager.GetString("ex_empty_decay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد وارد نشده است..
        /// </summary>
        internal static string ex_empty_num {
            get {
                return ResourceManager.GetString("ex_empty_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان عامل وارد نشده است..
        /// </summary>
        internal static string ex_empty_operativename {
            get {
                return ResourceManager.GetString("ex_empty_operativename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد  وارد نشده است..
        /// </summary>
        internal static string ex_empty_percent_value {
            get {
                return ResourceManager.GetString("ex_empty_percent_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزش ريالی تعیین نشده است..
        /// </summary>
        internal static string ex_empty_price {
            get {
                return ResourceManager.GetString("ex_empty_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد نشده است..
        /// </summary>
        internal static string ex_empty_price_value {
            get {
                return ResourceManager.GetString("ex_empty_price_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال وارد نشده است..
        /// </summary>
        internal static string ex_empty_serial {
            get {
                return ResourceManager.GetString("ex_empty_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سررسید را وارد نمایید..
        /// </summary>
        internal static string ex_enter_cheque_date {
            get {
                return ResourceManager.GetString("ex_enter_cheque_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره چک را وارد نمایید..
        /// </summary>
        internal static string ex_enter_cheque_number {
            get {
                return ResourceManager.GetString("ex_enter_cheque_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد نشده است..
        /// </summary>
        internal static string ex_enter_code {
            get {
                return ResourceManager.GetString("ex_enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارد نشده است..
        /// </summary>
        internal static string ex_enter_date {
            get {
                return ResourceManager.GetString("ex_enter_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق انتخاب نشده است..
        /// </summary>
        internal static string ex_enter_fund {
            get {
                return ResourceManager.GetString("ex_enter_fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وارد نشده است..
        /// </summary>
        internal static string ex_enter_price {
            get {
                return ResourceManager.GetString("ex_enter_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه تفصیلی تعیین نشده است..
        /// </summary>
        internal static string ex_goruh_not_found {
            get {
                return ResourceManager.GetString("ex_goruh_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_bankbranchcode {
            get {
                return ResourceManager.GetString("ex_invalid_bankbranchcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_bankname {
            get {
                return ResourceManager.GetString("ex_invalid_bankname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره چک تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_cheque_num {
            get {
                return ResourceManager.GetString("ex_invalid_cheque_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ چک را وارد نمایید..
        /// </summary>
        internal static string ex_invalid_cheque_price {
            get {
                return ResourceManager.GetString("ex_invalid_cheque_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد نادرست است..
        /// </summary>
        internal static string ex_invalid_code_length {
            get {
                return ResourceManager.GetString("ex_invalid_code_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_commodity_count {
            get {
                return ResourceManager.GetString("ex_invalid_commodity_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نادرست است..
        /// </summary>
        internal static string ex_invalid_count {
            get {
                return ResourceManager.GetString("ex_invalid_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای منطقی سامانه.
        /// </summary>
        internal static string ex_invalid_data {
            get {
                return ResourceManager.GetString("ex_invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف موجودی نادرست است..
        /// </summary>
        internal static string ex_invalid_max_Inventory {
            get {
                return ResourceManager.GetString("ex_invalid_max_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معین بستانکار تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_moein_creditor {
            get {
                return ResourceManager.GetString("ex_invalid_moein_creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معین بدهکار تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_moein_debtor {
            get {
                return ResourceManager.GetString("ex_invalid_moein_debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_name {
            get {
                return ResourceManager.GetString("ex_invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نادرست است..
        /// </summary>
        internal static string ex_invalid_num {
            get {
                return ResourceManager.GetString("ex_invalid_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ نادرست است..
        /// </summary>
        internal static string ex_invalid_price {
            get {
                return ResourceManager.GetString("ex_invalid_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل دریافت تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_recive_place {
            get {
                return ResourceManager.GetString("ex_invalid_recive_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دریافت کننده تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_reciver {
            get {
                return ResourceManager.GetString("ex_invalid_reciver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت رکورد انتخابی نادرست است..
        /// </summary>
        internal static string ex_invalid_record_status {
            get {
                return ResourceManager.GetString("ex_invalid_record_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دریافت تعیین نشده است..
        /// </summary>
        internal static string ex_invalid_revice_type {
            get {
                return ResourceManager.GetString("ex_invalid_revice_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار سال وارد شده معتبر نمیباشد.
        /// </summary>
        internal static string ex_invalid_salemali {
            get {
                return ResourceManager.GetString("ex_invalid_salemali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده برای تبدیل نادرست است..
        /// </summary>
        internal static string ex_invalid_unit_count_value {
            get {
                return ResourceManager.GetString("ex_invalid_unit_count_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل پیدا نشد..
        /// </summary>
        internal static string ex_kol_not_found {
            get {
                return ResourceManager.GetString("ex_kol_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی مقادیر الزامی میباشد.
        /// </summary>
        internal static string ex_moein_no_correct_data {
            get {
                return ResourceManager.GetString("ex_moein_no_correct_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد شمارش پایه انتخاب نشده است..
        /// </summary>
        internal static string ex_no_base_count_unit {
            get {
                return ResourceManager.GetString("ex_no_base_count_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور نا مشخص است..
        /// </summary>
        internal static string ex_no_bill_num {
            get {
                return ResourceManager.GetString("ex_no_bill_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ کالایی ثبت نشده است..
        /// </summary>
        internal static string ex_no_commodity_inserted {
            get {
                return ResourceManager.GetString("ex_no_commodity_inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا انتخاب نشده است..
        /// </summary>
        internal static string ex_no_commodity_seletced {
            get {
                return ResourceManager.GetString("ex_no_commodity_seletced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت انتخاب نشده است..
        /// </summary>
        internal static string ex_no_company_seletced {
            get {
                return ResourceManager.GetString("ex_no_company_seletced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت انتخاب نشده است..
        /// </summary>
        internal static string ex_no_corporartion {
            get {
                return ResourceManager.GetString("ex_no_corporartion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گروه اصلی وارد نشده است..
        /// </summary>
        internal static string ex_no_main_group_code {
            get {
                return ResourceManager.GetString("ex_no_main_group_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه اصلی وارد نشده است..
        /// </summary>
        internal static string ex_no_main_group_title {
            get {
                return ResourceManager.GetString("ex_no_main_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تکراری است..
        /// </summary>
        internal static string ex_no_owner_num {
            get {
                return ResourceManager.GetString("ex_no_owner_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت وارد نشده است..
        /// </summary>
        internal static string ex_no_price {
            get {
                return ResourceManager.GetString("ex_no_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ سطری انتخاب نشده است..
        /// </summary>
        internal static string ex_no_record_selected {
            get {
                return ResourceManager.GetString("ex_no_record_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار انتخاب نشده است..
        /// </summary>
        internal static string ex_no_repository_selected {
            get {
                return ResourceManager.GetString("ex_no_repository_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی را وارد نمایید.
        /// </summary>
        internal static string ex_no_salemali {
            get {
                return ResourceManager.GetString("ex_no_salemali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار تعیین نشده است..
        /// </summary>
        internal static string ex_no_stroes_selected {
            get {
                return ResourceManager.GetString("ex_no_stroes_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گروه فرعی وارد نشده است..
        /// </summary>
        internal static string ex_no_subsidiary_group_code {
            get {
                return ResourceManager.GetString("ex_no_subsidiary_group_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه فرعی وارد نشده است..
        /// </summary>
        internal static string ex_no_subsidiary_group_title {
            get {
                return ResourceManager.GetString("ex_no_subsidiary_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد شمارش تعیین نشده است..
        /// </summary>
        internal static string ex_no_unitcount_seletced {
            get {
                return ResourceManager.GetString("ex_no_unitcount_seletced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عامل انتخاب نشده است..
        /// </summary>
        internal static string ex_operative_not_selected {
            get {
                return ResourceManager.GetString("ex_operative_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عامل انتخاب نشده است..
        /// </summary>
        internal static string ex_operativetype_not_selected {
            get {
                return ResourceManager.GetString("ex_operativetype_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل پیدا نشد..
        /// </summary>
        internal static string ex_person_not_found {
            get {
                return ResourceManager.GetString("ex_person_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محل دریافت پیدا نشد..
        /// </summary>
        internal static string ex_reciveplace_not_found {
            get {
                return ResourceManager.GetString("ex_reciveplace_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دریافت مشخص نشده است..
        /// </summary>
        internal static string ex_recivetype_not_found {
            get {
                return ResourceManager.GetString("ex_recivetype_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گروه فرعی تکراری است..
        /// </summary>
        internal static string ex_subsidiarygroup_exists {
            get {
                return ResourceManager.GetString("ex_subsidiarygroup_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کد وارد شده گروه فرعی پیدا نشد..
        /// </summary>
        internal static string ex_subsidiarygroup_not_found {
            get {
                return ResourceManager.GetString("ex_subsidiarygroup_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه تفصیل پیدا نشد..
        /// </summary>
        internal static string ex_tafsillevel_not_found {
            get {
                return ResourceManager.GetString("ex_tafsillevel_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا واحد شمارش را انتخاب نمایید..
        /// </summary>
        internal static string ex_unit_count_is_mandatory {
            get {
                return ResourceManager.GetString("ex_unit_count_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        internal static string GoodsManagement {
            get {
                return ResourceManager.GetString("GoodsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم انتخاب شده دارای زیر مجموعه میباشد.
        /// </summary>
        internal static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیلی.
        /// </summary>
        internal static string HesabTafsil {
            get {
                return ResourceManager.GetString("HesabTafsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور فروش.
        /// </summary>
        internal static string InvoiceManagement {
            get {
                return ResourceManager.GetString("InvoiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول نمیتواند کمتر از حد تعیین شده باشد.
        /// </summary>
        internal static string MinRequementValue {
            get {
                return ResourceManager.GetString("MinRequementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معین.
        /// </summary>
        internal static string Moein {
            get {
                return ResourceManager.GetString("Moein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختار معین.
        /// </summary>
        internal static string MoeinSd {
            get {
                return ResourceManager.GetString("MoeinSd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد را به درستی وارد کنید.
        /// </summary>
        internal static string nullCode {
            get {
                return ResourceManager.GetString("nullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عنوان را به درستی وارد کنید.
        /// </summary>
        internal static string nullName {
            get {
                return ResourceManager.GetString("nullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عوامل فاکتور.
        /// </summary>
        internal static string OperativeManagement {
            get {
                return ResourceManager.GetString("OperativeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حواله.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختار پرسنل.
        /// </summary>
        internal static string PersonSd {
            get {
                return ResourceManager.GetString("PersonSd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فاکتور.
        /// </summary>
        internal static string PreInvoiceManagment {
            get {
                return ResourceManager.GetString("PreInvoiceManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور خرید.
        /// </summary>
        internal static string PurchaseInvoice {
            get {
                return ResourceManager.GetString("PurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید خرید.
        /// </summary>
        internal static string ReceiptManagement {
            get {
                return ResourceManager.GetString("ReceiptManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت گروه کالای اموال.
        /// </summary>
        internal static string RegisterAssetGoodGroup {
            get {
                return ResourceManager.GetString("RegisterAssetGoodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فاکتور خرید.
        /// </summary>
        internal static string RegisterBill {
            get {
                return ResourceManager.GetString("RegisterBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فاکتور فروش.
        /// </summary>
        internal static string RegisterInvoice {
            get {
                return ResourceManager.GetString("RegisterInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پیش فاکتور فروش.
        /// </summary>
        internal static string RegisterPreInvoice {
            get {
                return ResourceManager.GetString("RegisterPreInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت فاکتور خرید.
        /// </summary>
        internal static string RegisterSaleInvoice {
            get {
                return ResourceManager.GetString("RegisterSaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پیش فاکتور خرید.
        /// </summary>
        internal static string RegisterSalePreInvoice {
            get {
                return ResourceManager.GetString("RegisterSalePreInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور برگشت از خرید.
        /// </summary>
        internal static string ReturnOfBuying {
            get {
                return ResourceManager.GetString("ReturnOfBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت از فروش.
        /// </summary>
        internal static string ReturnOfSale {
            get {
                return ResourceManager.GetString("ReturnOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور فروش.
        /// </summary>
        internal static string SaleInvoice {
            get {
                return ResourceManager.GetString("SaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string Seperator {
            get {
                return ResourceManager.GetString("Seperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ضرایب مالیات.
        /// </summary>
        internal static string SOTaxForm {
            get {
                return ResourceManager.GetString("SOTaxForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عوامل موثر سطر پیش فاکتور.
        /// </summary>
        internal static string StoreDetailEffectiveOperative {
            get {
                return ResourceManager.GetString("StoreDetailEffectiveOperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عوامل غیر موثر سطر پیش فاکتور.
        /// </summary>
        internal static string StoreDetailInEffectiveOperative {
            get {
                return ResourceManager.GetString("StoreDetailInEffectiveOperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عوامل موثر پیش فاکتور.
        /// </summary>
        internal static string StoreOrderEffectiveOperative {
            get {
                return ResourceManager.GetString("StoreOrderEffectiveOperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عوامل غیر موثر پیش فاکتور.
        /// </summary>
        internal static string StoreOrderInEffectiveOperative {
            get {
                return ResourceManager.GetString("StoreOrderInEffectiveOperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفصیل 1.
        /// </summary>
        internal static string Tafsil1 {
            get {
                return ResourceManager.GetString("Tafsil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفصیل 2.
        /// </summary>
        internal static string Tafsil2 {
            get {
                return ResourceManager.GetString("Tafsil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفصیل 3.
        /// </summary>
        internal static string Tafsil3 {
            get {
                return ResourceManager.GetString("Tafsil3", resourceCulture);
            }
        }
    }
}
