//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingDocument
    {
        public System.Guid Id { get; set; }
        public string ADDescription { get; set; }
        public string ADDescriptionEn { get; set; }
        public string ADDate { get; set; }
        public Nullable<int> ADPriority { get; set; }
        public Nullable<int> ADCode { get; set; }
        public string ADOldCode { get; set; }
        public Nullable<bool> AISDeleted { get; set; }
        public Nullable<System.Guid> AIdStatus { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public Nullable<System.Guid> ADType { get; set; }
    }
}
