//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingArticle
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDAccountingDocument { get; set; }
        public string ADescription { get; set; }
        public string ADescriptionEn { get; set; }
        public Nullable<decimal> ADebtor { get; set; }
        public Nullable<decimal> ACreditor { get; set; }
        public Nullable<int> ACount { get; set; }
    }
}
