//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingTafsillevelsDetailView
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdCodeTitle { get; set; }
        public Nullable<System.Guid> IdAccountingTafsilLevels { get; set; }
        public string ATLName { get; set; }
        public string ATLNameEn { get; set; }
        public string IdIn { get; set; }
        public Nullable<System.Guid> IdRefrence { get; set; }
        public System.DateTime LastEdit { get; set; }
    }
}
