//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingMoein
    {
        public AccountingMoein()
        {
            this.AccountingMoeinDetails = new HashSet<AccountingMoeinDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string MName { get; set; }
        public string MIdGroup { get; set; }
        public string MIdAll { get; set; }
        public string MIdMoein { get; set; }
        public string MFName { get; set; }
        public string MFALLName { get; set; }
        public string MGrouhF { get; set; }
        public string MMoein { get; set; }
        public Nullable<System.Guid> MMoienType { get; set; }
    
        public virtual ICollection<AccountingMoeinDetail> AccountingMoeinDetails { get; set; }
    }
}
