//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingInterface
    {
        public System.Guid Id { get; set; }
        public Nullable<int> AIGroupID { get; set; }
        public string AIGroupName { get; set; }
        public string AIName { get; set; }
        public Nullable<System.Guid> AIDebtor_IDAccountingMoein { get; set; }
        public Nullable<System.Guid> AICreditor_IDAccountingMoein { get; set; }
        public Nullable<System.Guid> AIDebtor_IDAccountingMoeinTafsilLevels { get; set; }
        public Nullable<System.Guid> AICreditor_IDAccountingMoeinTafsilLevels { get; set; }
    }
}
