//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingMoeinDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdCodeTitle { get; set; }
        public Nullable<System.Guid> IdAccountingMoein { get; set; }
        public string MDName { get; set; }
        public string MDNameEn { get; set; }
        public string IdIn { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
    
        public virtual AccountingMoein AccountingMoein { get; set; }
        public virtual CodeTitle CodeTitle { get; set; }
    }
}
