//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingTafsilArticle
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IDAccountingMoeinTafsilLevels { get; set; }
        public Nullable<System.Guid> IdAccountingTafsilLDetails { get; set; }
        public Nullable<System.Guid> IdAccountingArticle { get; set; }
        public Nullable<System.Guid> IDAccountingMoein { get; set; }
        public Nullable<System.Guid> IDAccountingTafsilStructureDefine { get; set; }
    }
}
