//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetGood
    {
        public System.Guid ID { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> parentId { get; set; }
        public string uniquepath { get; set; }
        public Nullable<System.Guid> codetitleId { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
    }
}
