//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Idperson { get; set; }
        public Nullable<System.Guid> Idassetgoods { get; set; }
        public string assetdate { get; set; }
        public string asset_No { get; set; }
        public Nullable<decimal> amortization_Rate { get; set; }
        public Nullable<System.Guid> amortization_Method { get; set; }
        public Nullable<decimal> Accumulative_amortization { get; set; }
        public Nullable<decimal> decay_value { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> asset_number { get; set; }
    }
}
