//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalDetail
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDCapital { get; set; }
        public string CDDate { get; set; }
        public Nullable<decimal> CDPrice { get; set; }
        public string CDDescription { get; set; }
    }
}
