//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public Check()
        {
            this.CheckProcesses = new HashSet<CheckProcess>();
        }
    
        public System.Guid ID { get; set; }
        public string CNO { get; set; }
        public string CAccountnumber { get; set; }
        public Nullable<decimal> CPrice { get; set; }
        public string CDescription { get; set; }
        public string CDate { get; set; }
        public string CName { get; set; }
        public Nullable<System.Guid> CBank { get; set; }
        public Nullable<System.Guid> CType { get; set; }
    
        public virtual ICollection<CheckProcess> CheckProcesses { get; set; }
    }
}
