//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckProcess
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDCheck { get; set; }
        public Nullable<System.Guid> CPType { get; set; }
        public Nullable<System.DateTime> CPDate { get; set; }
        public string CPName { get; set; }
        public string CPDescription { get; set; }
        public Nullable<System.Guid> IDFunds { get; set; }
        public string CSerial { get; set; }
    
        public virtual Check Check { get; set; }
    }
}
