//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTitle
    {
        public CodeTitle()
        {
            this.AccountingMoeinDetails = new HashSet<AccountingMoeinDetail>();
            this.AccountingTafsillevelsDetails = new HashSet<AccountingTafsillevelsDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> CodeGroup { get; set; }
        public Nullable<int> CodeLen { get; set; }
        public Nullable<int> CodePriority { get; set; }
        public Nullable<int> CodeStart { get; set; }
    
        public virtual ICollection<AccountingMoeinDetail> AccountingMoeinDetails { get; set; }
        public virtual ICollection<AccountingTafsillevelsDetail> AccountingTafsillevelsDetails { get; set; }
    }
}
