//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com
    {
        public System.Guid Id { get; set; }
        public string CName { get; set; }
        public string CNameEn { get; set; }
        public Nullable<System.Guid> CPersonType { get; set; }
        public Nullable<int> CRegisterNo { get; set; }
        public string CNationalCode { get; set; }
        public string CEconomyCode { get; set; }
        public string CPostalCode { get; set; }
        public string CAddress { get; set; }
        public string CTell { get; set; }
        public string CMobile { get; set; }
        public string CFax { get; set; }
        public string CEMail { get; set; }
        public string CWebsite { get; set; }
        public Nullable<System.Guid> CPriceType { get; set; }
        public Nullable<System.Guid> CType { get; set; }
        public Nullable<System.Guid> IdTafsilLevels { get; set; }
        public Nullable<System.Guid> IdAccountingTafsillevelsDetails { get; set; }
        public Nullable<System.Guid> CompanyStructureDefineId { get; set; }
    }
}
