//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IDCodeTitle { get; set; }
        public Nullable<System.Guid> IDCompany { get; set; }
        public string CDName { get; set; }
        public string CDNameEn { get; set; }
        public string CDIDIn { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
    }
}
