//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class corporation
    {
        public System.Guid ID { get; set; }
        public string Groupname { get; set; }
        public string CorporationName { get; set; }
        public string mahale_sabt { get; set; }
        public string CorporationType { get; set; }
        public string phone { get; set; }
        public string sabt { get; set; }
        public string idposti { get; set; }
        public string address { get; set; }
        public byte[] image_byte { get; set; }
        public string kod_kargah { get; set; }
        public string radif_peyman { get; set; }
        public string nameshobe_bime { get; set; }
        public string name_kargah { get; set; }
        public string kod_shemely { get; set; }
        public string nerkhe_bime { get; set; }
        public string sh_parvande { get; set; }
        public string kod_shobe { get; set; }
        public string noeasliepardakhtkonande { get; set; }
        public string noefareiepardakhtkonande { get; set; }
        public string name_shobe { get; set; }
        public string nahve_maliyat { get; set; }
        public string pardakht_name { get; set; }
        public string pardakht_family { get; set; }
        public string pardakht_codemelli { get; set; }
        public string kod_egtesady { get; set; }
        public string nahve_pardakht { get; set; }
        public string emza1_name { get; set; }
        public string emza1_family { get; set; }
        public string emza1_codemelli { get; set; }
        public string emza1_semat { get; set; }
        public string kod_TFN { get; set; }
        public string kod_TIN { get; set; }
    }
}
