//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financialyear
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDCorporation { get; set; }
        public Nullable<int> FYyear { get; set; }
        public Nullable<int> FYMonthNO { get; set; }
        public string FYMonthName { get; set; }
        public Nullable<int> FYMonthNumber { get; set; }
        public Nullable<int> piroity { get; set; }
    }
}
