//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodiesGroupsView
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string CName { get; set; }
        public string CNameEn { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string uniquepath { get; set; }
        public Nullable<System.Guid> CodeTitleId { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
    }
}
