//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodyConvertCountingUnit
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDCommodity { get; set; }
        public Nullable<System.Guid> CCCUIDBaseInfo1 { get; set; }
        public Nullable<int> CCCUCount1 { get; set; }
        public Nullable<System.Guid> CCCUIDBaseInfo2 { get; set; }
        public Nullable<int> CCCUCount2 { get; set; }
    }
}
