//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operative
    {
        public Operative()
        {
            this.StoreOperatives = new HashSet<StoreOperative>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<bool> OISEffective { get; set; }
        public string OName { get; set; }
        public Nullable<System.Guid> OType { get; set; }
        public Nullable<System.Guid> OCalculationMethod { get; set; }
        public Nullable<decimal> OPercent { get; set; }
    
        public virtual ICollection<StoreOperative> StoreOperatives { get; set; }
    }
}
