//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollInsuranceCode
    {
        public System.Guid Id { get; set; }
        public Nullable<int> MCode { get; set; }
        public string MDesc { get; set; }
        public Nullable<int> SCode { get; set; }
        public string SDesc { get; set; }
    }
}
