//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollSentence
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PrSType { get; set; }
        public Nullable<System.Guid> PrSOType { get; set; }
        public string PrSDescription { get; set; }
        public Nullable<decimal> PrSMoney { get; set; }
        public Nullable<bool> PrSIsInsurance { get; set; }
        public Nullable<bool> PrSIsTax { get; set; }
        public string PrSInsuranceEmployer { get; set; }
        public string PrSInsuranceUnemployment { get; set; }
        public string PrSInsuranceEmployee { get; set; }
    }
}
