//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollInsuranceimmunity
    {
        public System.Guid ID { get; set; }
        public Nullable<int> kod_moafiat { get; set; }
        public string name_moafiat { get; set; }
        public Nullable<double> personel_dasad { get; set; }
        public Nullable<double> bikari_darsad { get; set; }
        public Nullable<double> karfarma_darsad { get; set; }
    }
}
