//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPerson
    {
        public System.Guid id { get; set; }
        public string PPerson_Code { get; set; }
        public string PFristName { get; set; }
        public string PLastName { get; set; }
        public string PFather { get; set; }
        public string PIdNational { get; set; }
        public string PSHSH { get; set; }
        public string PBrithDate { get; set; }
        public Nullable<System.Guid> PSex { get; set; }
        public Nullable<System.Guid> PMarriage { get; set; }
        public Nullable<int> PNumberChild { get; set; }
        public string PPhoneHome { get; set; }
        public string PPhoneWork { get; set; }
        public string PMobile { get; set; }
        public string PIdPostal { get; set; }
        public string PAddress { get; set; }
        public string PDescription { get; set; }
        public byte[] PImage { get; set; }
        public Nullable<int> Tax_madrak { get; set; }
        public Nullable<int> Tax_onvanShoghl { get; set; }
        public Nullable<int> Tax_serishenasnameh { get; set; }
        public Nullable<int> Tax_vazmaskan { get; set; }
        public Nullable<int> Tax_meliat { get; set; }
        public Nullable<int> Tax_namekeshvar { get; set; }
        public Nullable<System.Guid> Tax_nezamvazifeh { get; set; }
        public Nullable<int> Tax_rasteshoghli { get; set; }
        public Nullable<int> Tax_vazmashin { get; set; }
        public Nullable<int> code_moafiat_maliat { get; set; }
        public Nullable<int> Insurance_keshvar { get; set; }
        public Nullable<int> Insurance_shahr { get; set; }
        public string Insurance_mashagel { get; set; }
        public Nullable<int> Insurance_tahsilat { get; set; }
        public Nullable<int> Insurance_reshteh { get; set; }
        public string Insurance_meliat { get; set; }
        public Nullable<int> code_moafiat_bimeh { get; set; }
        public Nullable<System.Guid> PersonStructerID { get; set; }
    
        public virtual PersonStructureDefine PersonStructureDefine { get; set; }
    }
}
