//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollLoanDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid IDPayrollLoan { get; set; }
        public string PrLDate { get; set; }
        public System.DateTime PrLDateMiladi { get; set; }
        public decimal PrLPrice { get; set; }
        public Nullable<bool> PrLPayment { get; set; }
    }
}
