//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollContract
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDFinancialyear { get; set; }
        public Nullable<System.Guid> IDPayrollPerson { get; set; }
        public string PrCContractNumber { get; set; }
        public Nullable<int> PrcContractType { get; set; }
        public string PrcDateContractRegister { get; set; }
        public string PrcDateContractStart { get; set; }
        public string PrcDateContractEmployment { get; set; }
        public string PrcDateContractEnd { get; set; }
        public string PrcDateContractExpire { get; set; }
        public Nullable<int> PrcInsuranceType { get; set; }
        public string PrcInsuranceNumber { get; set; }
        public Nullable<System.Guid> PrcSalaryType { get; set; }
        public string PrcSalary { get; set; }
        public string PrCBankName { get; set; }
        public string PrCBranchName { get; set; }
        public string PrCAccountNumber { get; set; }
        public string PrCBranchCartNumber { get; set; }
    }
}
