//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollTaximmunity
    {
        public System.Guid ID { get; set; }
        public int tmpid { get; set; }
        public Nullable<int> kod_moafiat { get; set; }
        public string name_moafiat { get; set; }
        public Nullable<decimal> money1 { get; set; }
        public Nullable<double> darsad1 { get; set; }
    }
}
