//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonStructureDefine
    {
        public PersonStructureDefine()
        {
            this.PayrollPersons = new HashSet<PayrollPerson>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> Type { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public string Uniq_Path { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
    
        public virtual ICollection<PayrollPerson> PayrollPersons { get; set; }
    }
}
