//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOTaxView
    {
        public System.Guid Id { get; set; }
        public System.Guid IdBaseinfo { get; set; }
        public System.Guid IdFinancialMainYear { get; set; }
        public decimal Percent { get; set; }
        public string AssignName { get; set; }
        public Nullable<System.Guid> IDCorporation { get; set; }
        public Nullable<int> FYear { get; set; }
    }
}
