//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public System.Guid Id { get; set; }
        public System.Guid IdStoreOrderDetail { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> SCount { get; set; }
        public Nullable<int> SRemained { get; set; }
        public Nullable<System.Guid> Sname { get; set; }
        public Nullable<System.Guid> IdStoreOperation { get; set; }
        public Nullable<System.Guid> IdCommodity { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
