//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOperative
    {
        public System.Guid Id { get; set; }
        public System.Guid IdStoreOrder { get; set; }
        public Nullable<System.Guid> IdStoreDetail { get; set; }
        public System.Guid IdOperative { get; set; }
        public Nullable<decimal> SPrice { get; set; }
    
        public virtual Operative Operative { get; set; }
        public virtual StoreOrder StoreOrder { get; set; }
        public virtual StoreOrderDetail StoreOrderDetail { get; set; }
    }
}
