//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryDetailsView
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDTreasury { get; set; }
        public Nullable<System.Guid> TDType { get; set; }
        public Nullable<decimal> TDPrice { get; set; }
        public Nullable<System.Guid> IDCheck { get; set; }
        public Nullable<System.Guid> IDFund { get; set; }
        public string TDDescription { get; set; }
        public string AssignName { get; set; }
        public string TDate { get; set; }
        public string Accountnumber { get; set; }
    }
}
