//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treasury
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Ttype { get; set; }
        public string TNO { get; set; }
        public string TDescription { get; set; }
        public string TDate { get; set; }
        public Nullable<decimal> TPrice { get; set; }
        public System.DateTime LastEdit { get; set; }
    }
}
